addons:
  apt:
    packages:
    - libasound2-dev

language: rust

cache: cargo

sudo: true

branches: master

os: -linux

git:
  depth: 1
rust:
  - stable

name: "q-moose"

before_script:
- cargo update
- sudo apt-get install libasound2-dev

script:
- cargo build --release --features="libc glium winit" --verbose --all
