addons:
  apt:
    packages:
    - libasound2-dev

language: rust

cache: cargo

sudo: false

branches: master

os: -linux

git:
  depth: 1
rust:
  - 1.28.0

name: "q-moose"

before_script:
- cargo update
- apt-get install libasound2-dev

script:
- cargo build --release --features="libc glium winit" --verbose --all
