language: rust
cache: cargo
sudo: true
branches: master
os: -linux
git:
  depth: 1
rust:
  - 1.28.0
rustup:
  - 1.13.0
addons:
  apt:
    packages:
    - libasound2-dev
name: "q-moose"
before_script:
- sudo apt install libasound2-dev
- cargo update
script:
- cargo build --release --features="libc glium winit" --verbose --all
